-- Simple Neo-tree configuration
return {
  "nvim-neo-tree/neo-tree.nvim",
  opts = {
    close_if_last_window = false,
    popup_border_style = "rounded",
    enable_git_status = true,
    enable_diagnostics = true,
    filesystem = {
      follow_current_file = false,
      hijack_netrw_behavior = "open_default",
      window = {
        mappings = {
          ["<bs>"] = "navigate_up",
          ["."] = "set_root",
          ["H"] = "toggle_hidden",
          ["/"] = "fuzzy_finder",
          ["D"] = "fuzzy_finder_directory",
        },
      },
    },
    window = {
      position = "left",
      width = 40,
      mappings = {
        ["<space>"] = "toggle_node",
        ["<cr>"] = "open",
        ["<esc>"] = "revert_preview",
        ["P"] = { "toggle_preview", config = { use_float = true } },
        ["l"] = "focus_preview",
        ["S"] = "open_split",
        ["s"] = "open_vsplit",
        ["t"] = "open_tabnew",
        ["w"] = "open_with_window_picker",
        ["C"] = "close_node",
        ["z"] = "close_all_nodes",
        ["R"] = "refresh",
        ["a"] = "add",
        ["A"] = "add_directory",
        ["d"] = "delete",
        ["r"] = "rename",
        ["y"] = "copy_to_clipboard",
        ["x"] = "cut_to_clipboard",
        ["p"] = "paste_from_clipboard",
        ["c"] = "copy",
        ["m"] = "move",
        ["q"] = "close_window",
      },
    },
  },
  keys = {
    { "<leader>e", "<cmd>Neotree toggle<cr>", desc = "  File Explorer  " },
    { "<leader>ge", "<cmd>Neotree git_status<cr>", desc = "  Git Explorer  " },
    { "<leader>be", "<cmd>Neotree buffers<cr>", desc = "  Buffer Explorer  " },
    { "<leader>nh", "<cmd>cd ~ | Neotree reveal<cr>", desc = "  Neo-tree Home  " },
    { "<leader>nr", "<cmd>Neotree reveal<cr>", desc = "  Reset Neo-tree  " },
    { "<leader>nu", "<cmd>cd .. | Neotree reveal<cr>", desc = "  Neo-tree Up  " },
  },
}